export const ACTION_TYPES = {
  OPEN_MODAL: "OPEN_MODAL",
  CLOSE_MODAL: "CLOSE_MODAL",

  //auth
  ON_CHANGE_NAME: "ON_CHANGE_NAME",
  ON_CHANGE_PASSWORD: "ON_CHANGE_PASSWORD",
  SIGN_IN_START: "SIGN_IN_START",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_FAILURE: "SIGN_IN_FAILURE",
  SIGN_OUT: "SIGN_OUT",
};
